apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka1
  namespace: cenote
  labels:
    app: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: issel/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-svc1
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka2
  namespace: cenote
  labels:
    app: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: issel/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-svc2
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka3
  namespace: cenote
  labels:
    app: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: issel/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-svc3
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-svc1
  namespace: cenote
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: 9092k1
  selector:
    app: kafka1
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-svc2
  namespace: cenote
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: 9092k2
  selector:
    app: kafka2
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-svc3
  namespace: cenote
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: 9092k3
  selector:
    app: kafka3
