apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka
  namespace: cenote-dev
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: issel/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-svc
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-svc
  namespace: cenote-dev
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: 9092k1
  selector:
    app: kafka
